# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0002_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages_post', to='user_dash.User'),
            preserve_default=False,
        ),
    ]
